main: me.wilux.blockshelf.Main
name: Blockshelf
version: 0.1
author: wilux
api-version: 1.13
depend: [ProtocolLib]
load: POSTWORLD
commands:
  customutils:
  rpsend:
    description: debug command
    usage: /rpsend
  rpdelete:
    description: debug command
    usage: /rpdelete
  setability:
    description: debug command
    usage: /setability